dependencies:
  # - organization/repo_name@version_number
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
dotenv: .env
networks:
  default: development
  kovan:
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
    verify_source: true
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify_source: false
  developmet:
    verify_source: false
  ganache-local:
    verify_source: false
wallets:
  from_key: ${PRIVATE_KEY}
